version: '3.4'
#http://www.inanzzz.com/index.php/post/zpbw/creating-a-simple-php-fpm-nginx-and-mysql-application-with-docker-compose
services:
    php:
        build:
            context: ./docker/php
        container_name: php_fpm
        networks:
            static_network:
                ipv4_address: 172.19.128.2
        ports:
            - 9000:9000
        volumes:
            - ./web/:/var/www/html
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
    nginx:
        build:
            context: ./docker/nginx
        container_name: nginx_server
        networks:
            static_network:
                ipv4_address: 172.19.128.3
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./web/:/var/www/html/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/app.vhost:/etc/nginx/conf.d/app.vhost
            # - ./docker/nginx/app.vhost:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/:/var/log/nginx
        depends_on:
            - php
    mysql:
        build:
            context: ./docker/mysql
        container_name: mysql_db
        networks:
            static_network:
                ipv4_address: 172.19.128.4
        ports:
            - 33006:3306
        volumes:
            - ./docker/mysql/data/:/var/lib/mysql
        depends_on:
            - php
        external_links:
            - mysql_mysql_1:docker-mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            DB_HOST: docker-mysql
        restart: always

    composer:
      image: "composer"
      volumes:
        - ./web/:/var/www/html
      command: "install"
      working_dir: /var/www/html

networks:
  static_network:
    ipam:
      config:
        - subnet: 172.19.0.0/16